"""Configuration schemas for sub-agents.

These schemas define the structure of sub-agent configuration.
The configuration is stored in subagent_config.py (AI generated by /onboard).
"""

from typing import Optional

from pydantic import BaseModel, Field


class ToolParameterConfig(BaseModel):
    """Configuration for a tool parameter."""

    name: str = Field(..., description="Parameter name")
    type: str = Field(default="str", description="Parameter type")
    description: str = Field(..., description="Parameter description for LLM")
    required: bool = Field(default=True, description="Whether required")
    default: Optional[str] = Field(default=None, description="Default value")


class ToolConfig(BaseModel):
    """Configuration for a tool."""

    name: str = Field(..., description="Tool function name (snake_case)")
    description: str = Field(..., description="Tool description for LLM")
    parameters: list[ToolParameterConfig] = Field(default_factory=list)
    return_type: str = Field(default="str", description="Return type")
    implementation_hint: Optional[str] = Field(default=None, description="Implementation hint")


class UseCaseConfig(BaseModel):
    """A use case for an agent - helps triage understand when to route here."""

    intent: str = Field(..., description="What user wants to accomplish")
    example_queries: list[str] = Field(
        default_factory=list, description="Example user queries for this use case"
    )


class SubAgentConfig(BaseModel):
    """Configuration for a sub-agent."""

    key: str = Field(..., description="Unique identifier (snake_case)")
    name: str = Field(..., description="Display name")
    description: str = Field(..., description="One-line description")
    capabilities: list[str] = Field(..., description="List of capabilities")
    tools: list[ToolConfig] = Field(default_factory=list, description="Tools for this agent")
    instructions: Optional[str] = Field(default=None, description="Custom system prompt")

    # Context for orchestration agents (used by Claude when filling prompts)
    use_cases: list[UseCaseConfig] = Field(
        default_factory=list, description="Use cases with example queries"
    )
    when_to_use: list[str] = Field(
        default_factory=list, description="Scenarios where triage should route here"
    )
    when_not_to_use: list[str] = Field(
        default_factory=list, description="Scenarios where another agent is better"
    )
