"""Sub-Agent Configuration (AI Generated).

This file is generated by the /onboard skill.
It contains the configuration for all sub-agents in your application.

DO NOT manually edit the SUB_AGENTS list - use /onboard to regenerate.
"""

from .schemas.config import SubAgentConfig, ToolConfig

# =============================================================================
# DOMAIN CONFIGURATION (AI Generated)
# =============================================================================

DOMAIN_NAME = "Default Assistant"
DOMAIN_DESCRIPTION = "This is a placeholder. Run /onboard to create your application."

# =============================================================================
# SUB-AGENTS CONFIGURATION (AI Generated)
# =============================================================================

SUB_AGENTS: list[SubAgentConfig] = [
    # Example (will be replaced by /onboard):
    # SubAgentConfig(
    #     key="leave",
    #     name="leave-agent",
    #     description="Handles vacation and leave requests",
    #     capabilities=["Check leave balance", "Submit leave requests"],
    #     tools=[
    #         ToolConfig(name="get_leave_balance", description="Get remaining leave days"),
    #         ToolConfig(name="submit_leave", description="Submit a leave request"),
    #     ],
    # ),
]
