"""Prompt templates for orchestration agents."""

from .templates import (
    CLARIFY_TEMPLATE,
    PLAN_TEMPLATE,
    REJECTION_MESSAGE_TEMPLATE,
    REPLAN_TEMPLATE,
    REVIEW_TEMPLATE,
    SUMMARY_TEMPLATE,
    TRIAGE_TEMPLATE,
)

__all__ = [
    "TRIAGE_TEMPLATE",
    "PLAN_TEMPLATE",
    "REPLAN_TEMPLATE",
    "REVIEW_TEMPLATE",
    "CLARIFY_TEMPLATE",
    "SUMMARY_TEMPLATE",
    "REJECTION_MESSAGE_TEMPLATE",
]
